const TASK_GROUPS = [
  {
    name: 'daily',
    label: '日常',
    tasks: [
      'startBatch',
      'claimHangUpRewards',
      'batchAddHangUpTime',
      'resetBottles',
      'batchlingguanzi',
      'batchclubsign',
      'batchStudy',
      'batcharenafight',
      'batchSmartSendCar',
      'batchClaimCars',
      'store_purchase',
      'collection_claimfreereward',
      'batchGenieSweep',
    ],
  },
  {
    name: 'dungeon',
    label: '副本',
    tasks: [
      'climbTower',
      'batchmengjing',
      'skinChallenge',
      'batchClaimPeachTasks',
      'batchBuyDreamItems',
    ],
  },
  { name: 'baoku', label: '宝库', tasks: ['batchbaoku13', 'batchbaoku45'] },
  {
    name: 'weirdTower',
    label: '怪异塔',
    tasks: [
      'climbWeirdTower',
      'batchUseItems',
      'batchMergeItems',
      'batchClaimFreeEnergy',
    ],
  },
  {
    name: 'resource',
    label: '资源',
    tasks: [
      'batchOpenBox',
      'batchOpenBoxByPoints',
      'batchClaimBoxPointReward',
      'batchFish',
      'batchRecruit',
      'legion_storebuygoods',
    ],
  },
  {
    name: 'legacy',
    label: '功法',
    tasks: ['batchLegacyClaim', 'batchLegacyGiftSendEnhanced'],
  },
  {
    name: 'monthly',
    label: '月度',
    tasks: ['batchTopUpFish', 'batchTopUpArena'],
  },
];

const BATCH_TASKS = [
  { label: '日常任务', value: 'startBatch' },
  { label: '领取挂机', value: 'claimHangUpRewards' },
  { label: '一键加钟', value: 'batchAddHangUpTime' },
  { label: '重置罐子', value: 'resetBottles' },
  { label: '一键领取罐子', value: 'batchlingguanzi' },
  { label: '一键爬塔', value: 'climbTower' },
  { label: '一键爬怪异塔', value: 'climbWeirdTower' },
  { label: '一键答题', value: 'batchStudy' },
  { label: '智能发车', value: 'batchSmartSendCar' },
  { label: '一键收车', value: 'batchClaimCars' },
  { label: '批量开箱', value: 'batchOpenBox' },
  { label: '按积分开箱', value: 'batchOpenBoxByPoints' },
  { label: '领取宝箱积分', value: 'batchClaimBoxPointReward' },
  { label: '批量钓鱼', value: 'batchFish' },
  { label: '批量招募', value: 'batchRecruit' },
  { label: '一键宝库前3层', value: 'batchbaoku13' },
  { label: '一键宝库4,5层', value: 'batchbaoku45' },
  { label: '一键梦境', value: 'batchmengjing' },
  { label: '一键俱乐部签到', value: 'batchclubsign' },
  { label: '一键竞技场战斗3次', value: 'batcharenafight' },
  { label: '一键钓鱼补齐', value: 'batchTopUpFish' },
  { label: '一键竞技场补齐', value: 'batchTopUpArena' },
  { label: '一键领取怪异塔免费道具', value: 'batchClaimFreeEnergy' },
  { label: '一键换皮闯关', value: 'skinChallenge' },
  { label: '一键购买四圣碎片', value: 'legion_storebuygoods' },
  { label: '一键黑市采购', value: 'store_purchase' },
  { label: '免费领取珍宝阁', value: 'collection_claimfreereward' },
  { label: '批量领取功法残卷', value: 'batchLegacyClaim' },
  { label: '批量赠送功法残卷', value: 'batchLegacyGiftSendEnhanced', requiresSettings: ['recipientId', 'password'] },
  { label: '一键使用怪异塔道具', value: 'batchUseItems' },
  { label: '一键怪异塔合成', value: 'batchMergeItems' },
  { label: '一键领取蟠桃园任务', value: 'batchClaimPeachTasks' },
  { label: '一键扫荡灯神', value: 'batchGenieSweep' },
  { label: '一键购买梦境商品', value: 'batchBuyDreamItems', requiresSettings: ['dreamPurchaseList'] },
].map((task) => ({
  ...task,
  group: TASK_GROUPS.find((group) => group.tasks.includes(task.value))?.name || 'other',
}));

const LEGACY_TASK_ALIASES = {
  daily_all: 'startBatch',
  hangup: 'claimHangUpRewards',
  hangup_time: 'batchAddHangUpTime',
  bottle_timer: 'resetBottles',
  bottle: 'batchlingguanzi',
  study: 'batchStudy',
  arena: 'batcharenafight',
  mail: 'mail',
  legion_signin: 'batchclubsign',
  gacha: 'gacha',
  recruit: 'recruit',
  buygold: 'buygold',
  daily_share: 'daily_share',
  friend: 'friend',
  daily_reward: 'daily_reward',
  daily_point: 'daily_point',
  weekly_reward: 'weekly_reward',
  war_order: 'war_order',
  open_box: 'batchOpenBox',
  legion_boss: 'legion_boss',
  daily_gift: 'daily_gift',
  collection: 'collection_claimfreereward',
  fishing: 'batchFish',
  genie: 'batchGenieSweep',
  black_market: 'store_purchase',
  dream: 'batchmengjing',
  boss: 'boss',
  tower: 'climbTower',
};

const TASK_VALUES = new Set([
  'task_group',
  ...BATCH_TASKS.map((task) => task.value),
  ...Object.keys(LEGACY_TASK_ALIASES),
  'mail',
  'gacha',
  'recruit',
  'buygold',
  'daily_share',
  'friend',
  'daily_reward',
  'daily_point',
  'weekly_reward',
  'war_order',
  'legion_boss',
  'daily_gift',
  'boss',
]);

function isValidTaskType(taskType) {
  return TASK_VALUES.has(taskType);
}

module.exports = {
  BATCH_TASKS,
  TASK_GROUPS,
  LEGACY_TASK_ALIASES,
  TASK_VALUES,
  isValidTaskType,
};
